# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add Nuget Source
      run: |
        dotnet nuget add source --username ${{ secrets.PACKAGE_WRITE_USERNAME }} --password ${{ secrets.PACKAGE_WRITE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/innago-property-management/index.json"
    - name: Extract Branch Name
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - name: Semver
      id: semver
      uses: ietf-tools/semver-action@v1.9.0
      with:
        token: ${{ secrets.SEMVER_TOKEN }}
        noNewCommitBehavior: 'silent'
        noVersionBumpBehavior: 'patch'
    - name: Version Variable
      run: echo "VERSION=${{ steps.semver.outputs.nextStrict }}" >> "$GITHUB_ENV"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore --configuration Release -p:Version="$VERSION" -p:AssemblyVersion="$VERSION"
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal -p:CollectCoverage=true
    - name: Publish
      if: env.BRANCH == 'main'
      run: |
        SOURCE_ROOT=${SOURCE_ROOT:-"src"}
        for file in "$SOURCE_ROOT"/**/bin/Release/*.nupkg; do
          dotnet nuget push "$file" --source github --skip-duplicate
        done
